const ELEMENTS = [
  // Periode 1
  {z:1,  sym:'H',  name:'Wasserstoff',    mass:1,   group:1,  period:1, cat:'nonmetal',    col:1,  row:1},
  {z:2,  sym:'He', name:'Helium',         mass:4,   group:18, period:1, cat:'noble',       col:18, row:1},
  // Periode 2
  {z:3,  sym:'Li', name:'Lithium',        mass:7,   group:1,  period:2, cat:'alkali',      col:1,  row:2},
  {z:4,  sym:'Be', name:'Beryllium',      mass:9,   group:2,  period:2, cat:'alkali-earth', col:2, row:2},
  {z:5,  sym:'B',  name:'Bor',            mass:11,  group:13, period:2, cat:'metalloid',   col:13, row:2},
  {z:6,  sym:'C',  name:'Kohlenstoff',    mass:12,  group:14, period:2, cat:'nonmetal',    col:14, row:2},
  {z:7,  sym:'N',  name:'Stickstoff',     mass:14,  group:15, period:2, cat:'nonmetal',    col:15, row:2},
  {z:8,  sym:'O',  name:'Sauerstoff',     mass:16,  group:16, period:2, cat:'nonmetal',    col:16, row:2},
  {z:9,  sym:'F',  name:'Fluor',          mass:19,  group:17, period:2, cat:'halogen',     col:17, row:2},
  {z:10, sym:'Ne', name:'Neon',           mass:20,  group:18, period:2, cat:'noble',       col:18, row:2},
  // Periode 3
  {z:11, sym:'Na', name:'Natrium',        mass:23,  group:1,  period:3, cat:'alkali',      col:1,  row:3},
  {z:12, sym:'Mg', name:'Magnesium',      mass:24,  group:2,  period:3, cat:'alkali-earth', col:2, row:3},
  {z:13, sym:'Al', name:'Aluminium',      mass:27,  group:13, period:3, cat:'post-trans',  col:13, row:3},
  {z:14, sym:'Si', name:'Silizium',       mass:28,  group:14, period:3, cat:'metalloid',   col:14, row:3},
  {z:15, sym:'P',  name:'Phosphor',       mass:31,  group:15, period:3, cat:'nonmetal',    col:15, row:3},
  {z:16, sym:'S',  name:'Schwefel',       mass:32,  group:16, period:3, cat:'nonmetal',    col:16, row:3},
  {z:17, sym:'Cl', name:'Chlor',          mass:35,  group:17, period:3, cat:'halogen',     col:17, row:3},
  {z:18, sym:'Ar', name:'Argon',          mass:40,  group:18, period:3, cat:'noble',       col:18, row:3},
  // Periode 4
  {z:19, sym:'K',  name:'Kalium',         mass:39,  group:1,  period:4, cat:'alkali',      col:1,  row:4},
  {z:20, sym:'Ca', name:'Calcium',        mass:40,  group:2,  period:4, cat:'alkali-earth', col:2, row:4},
  {z:21, sym:'Sc', name:'Scandium',       mass:45,  group:3,  period:4, cat:'transition',  col:3,  row:4},
  {z:22, sym:'Ti', name:'Titan',          mass:48,  group:4,  period:4, cat:'transition',  col:4,  row:4},
  {z:23, sym:'V',  name:'Vanadium',       mass:51,  group:5,  period:4, cat:'transition',  col:5,  row:4},
  {z:24, sym:'Cr', name:'Chrom',          mass:52,  group:6,  period:4, cat:'transition',  col:6,  row:4},
  {z:25, sym:'Mn', name:'Mangan',         mass:55,  group:7,  period:4, cat:'transition',  col:7,  row:4},
  {z:26, sym:'Fe', name:'Eisen',          mass:56,  group:8,  period:4, cat:'transition',  col:8,  row:4},
  {z:27, sym:'Co', name:'Kobalt',         mass:59,  group:9,  period:4, cat:'transition',  col:9,  row:4},
  {z:28, sym:'Ni', name:'Nickel',         mass:58,  group:10, period:4, cat:'transition',  col:10, row:4},
  {z:29, sym:'Cu', name:'Kupfer',         mass:64,  group:11, period:4, cat:'transition',  col:11, row:4},
  {z:30, sym:'Zn', name:'Zink',           mass:65,  group:12, period:4, cat:'transition',  col:12, row:4},
  {z:31, sym:'Ga', name:'Gallium',        mass:70,  group:13, period:4, cat:'post-trans',  col:13, row:4},
  {z:32, sym:'Ge', name:'Germanium',      mass:73,  group:14, period:4, cat:'metalloid',   col:14, row:4},
  {z:33, sym:'As', name:'Arsen',          mass:75,  group:15, period:4, cat:'metalloid',   col:15, row:4},
  {z:34, sym:'Se', name:'Selen',          mass:79,  group:16, period:4, cat:'nonmetal',    col:16, row:4},
  {z:35, sym:'Br', name:'Brom',           mass:80,  group:17, period:4, cat:'halogen',     col:17, row:4},
  {z:36, sym:'Kr', name:'Krypton',        mass:84,  group:18, period:4, cat:'noble',       col:18, row:4},
  // Periode 5
  {z:37, sym:'Rb', name:'Rubidium',       mass:85,  group:1,  period:5, cat:'alkali',      col:1,  row:5},
  {z:38, sym:'Sr', name:'Strontium',      mass:88,  group:2,  period:5, cat:'alkali-earth', col:2, row:5},
  {z:39, sym:'Y',  name:'Yttrium',        mass:89,  group:3,  period:5, cat:'transition',  col:3,  row:5},
  {z:40, sym:'Zr', name:'Zirconium',      mass:91,  group:4,  period:5, cat:'transition',  col:4,  row:5},
  {z:41, sym:'Nb', name:'Niob',           mass:93,  group:5,  period:5, cat:'transition',  col:5,  row:5},
  {z:42, sym:'Mo', name:'Molybdän',       mass:96,  group:6,  period:5, cat:'transition',  col:6,  row:5},
  {z:43, sym:'Tc', name:'Technetium',     mass:98,  group:7,  period:5, cat:'transition',  col:7,  row:5},
  {z:44, sym:'Ru', name:'Ruthenium',      mass:101, group:8,  period:5, cat:'transition',  col:8,  row:5},
  {z:45, sym:'Rh', name:'Rhodium',        mass:103, group:9,  period:5, cat:'transition',  col:9,  row:5},
  {z:46, sym:'Pd', name:'Palladium',      mass:106, group:10, period:5, cat:'transition',  col:10, row:5},
  {z:47, sym:'Ag', name:'Silber',         mass:108, group:11, period:5, cat:'transition',  col:11, row:5},
  {z:48, sym:'Cd', name:'Cadmium',        mass:112, group:12, period:5, cat:'transition',  col:12, row:5},
  {z:49, sym:'In', name:'Indium',         mass:115, group:13, period:5, cat:'post-trans',  col:13, row:5},
  {z:50, sym:'Sn', name:'Zinn',           mass:119, group:14, period:5, cat:'post-trans',  col:14, row:5},
  {z:51, sym:'Sb', name:'Antimon',        mass:122, group:15, period:5, cat:'metalloid',   col:15, row:5},
  {z:52, sym:'Te', name:'Tellur',         mass:128, group:16, period:5, cat:'metalloid',   col:16, row:5},
  {z:53, sym:'I',  name:'Iod',            mass:127, group:17, period:5, cat:'halogen',     col:17, row:5},
  {z:54, sym:'Xe', name:'Xenon',          mass:131, group:18, period:5, cat:'noble',       col:18, row:5},
  // Periode 6
  {z:55, sym:'Cs', name:'Caesium',        mass:133, group:1,  period:6, cat:'alkali',      col:1,  row:6},
  {z:56, sym:'Ba', name:'Barium',         mass:137, group:2,  period:6, cat:'alkali-earth', col:2, row:6},
  {z:57, sym:'La', name:'Lanthan',        mass:139, group:3,  period:6, cat:'lanthanide',  col:3,  row:6},
  {z:58, sym:'Ce', name:'Cer',            mass:140, group:3,  period:6, cat:'lanthanide',  col:4,  row:8},
  {z:59, sym:'Pr', name:'Praseodym',      mass:141, group:3,  period:6, cat:'lanthanide',  col:5,  row:8},
  {z:60, sym:'Nd', name:'Neodym',         mass:144, group:3,  period:6, cat:'lanthanide',  col:6,  row:8},
  {z:61, sym:'Pm', name:'Promethium',     mass:145, group:3,  period:6, cat:'lanthanide',  col:7,  row:8},
  {z:62, sym:'Sm', name:'Samarium',       mass:150, group:3,  period:6, cat:'lanthanide',  col:8,  row:8},
  {z:63, sym:'Eu', name:'Europium',       mass:152, group:3,  period:6, cat:'lanthanide',  col:9,  row:8},
  {z:64, sym:'Gd', name:'Gadolinium',     mass:157, group:3,  period:6, cat:'lanthanide',  col:10, row:8},
  {z:65, sym:'Tb', name:'Terbium',        mass:159, group:3,  period:6, cat:'lanthanide',  col:11, row:8},
  {z:66, sym:'Dy', name:'Dysprosium',     mass:163, group:3,  period:6, cat:'lanthanide',  col:12, row:8},
  {z:67, sym:'Ho', name:'Holmium',        mass:165, group:3,  period:6, cat:'lanthanide',  col:13, row:8},
  {z:68, sym:'Er', name:'Erbium',         mass:167, group:3,  period:6, cat:'lanthanide',  col:14, row:8},
  {z:69, sym:'Tm', name:'Thulium',        mass:169, group:3,  period:6, cat:'lanthanide',  col:15, row:8},
  {z:70, sym:'Yb', name:'Ytterbium',      mass:173, group:3,  period:6, cat:'lanthanide',  col:16, row:8},
  {z:71, sym:'Lu', name:'Lutetium',       mass:175, group:3,  period:6, cat:'lanthanide',  col:17, row:8},
  {z:72, sym:'Hf', name:'Hafnium',        mass:178, group:4,  period:6, cat:'transition',  col:4,  row:6},
  {z:73, sym:'Ta', name:'Tantal',         mass:181, group:5,  period:6, cat:'transition',  col:5,  row:6},
  {z:74, sym:'W',  name:'Wolfram',        mass:184, group:6,  period:6, cat:'transition',  col:6,  row:6},
  {z:75, sym:'Re', name:'Rhenium',        mass:186, group:7,  period:6, cat:'transition',  col:7,  row:6},
  {z:76, sym:'Os', name:'Osmium',         mass:190, group:8,  period:6, cat:'transition',  col:8,  row:6},
  {z:77, sym:'Ir', name:'Iridium',        mass:192, group:9,  period:6, cat:'transition',  col:9,  row:6},
  {z:78, sym:'Pt', name:'Platin',         mass:195, group:10, period:6, cat:'transition',  col:10, row:6},
  {z:79, sym:'Au', name:'Gold',           mass:197, group:11, period:6, cat:'transition',  col:11, row:6},
  {z:80, sym:'Hg', name:'Quecksilber',    mass:201, group:12, period:6, cat:'transition',  col:12, row:6},
  {z:81, sym:'Tl', name:'Thallium',       mass:204, group:13, period:6, cat:'post-trans',  col:13, row:6},
  {z:82, sym:'Pb', name:'Blei',           mass:207, group:14, period:6, cat:'post-trans',  col:14, row:6},
  {z:83, sym:'Bi', name:'Bismut',         mass:209, group:15, period:6, cat:'post-trans',  col:15, row:6},
  {z:84, sym:'Po', name:'Polonium',       mass:209, group:16, period:6, cat:'post-trans',  col:16, row:6},
  {z:85, sym:'At', name:'Astat',          mass:210, group:17, period:6, cat:'halogen',     col:17, row:6},
  {z:86, sym:'Rn', name:'Radon',          mass:222, group:18, period:6, cat:'noble',       col:18, row:6},
  // Periode 7
  {z:87, sym:'Fr', name:'Francium',       mass:223, group:1,  period:7, cat:'alkali',      col:1,  row:7},
  {z:88, sym:'Ra', name:'Radium',         mass:226, group:2,  period:7, cat:'alkali-earth', col:2, row:7},
  {z:89, sym:'Ac', name:'Actinium',       mass:227, group:3,  period:7, cat:'actinide',    col:3,  row:7},
  {z:90, sym:'Th', name:'Thorium',        mass:232, group:3,  period:7, cat:'actinide',    col:4,  row:9},
  {z:91, sym:'Pa', name:'Protactinium',   mass:231, group:3,  period:7, cat:'actinide',    col:5,  row:9},
  {z:92, sym:'U',  name:'Uran',           mass:238, group:3,  period:7, cat:'actinide',    col:6,  row:9},
  {z:93, sym:'Np', name:'Neptunium',      mass:237, group:3,  period:7, cat:'actinide',    col:7,  row:9},
  {z:94, sym:'Pu', name:'Plutonium',      mass:244, group:3,  period:7, cat:'actinide',    col:8,  row:9},
  {z:95, sym:'Am', name:'Americium',      mass:243, group:3,  period:7, cat:'actinide',    col:9,  row:9},
  {z:96, sym:'Cm', name:'Curium',         mass:247, group:3,  period:7, cat:'actinide',    col:10, row:9},
  {z:97, sym:'Bk', name:'Berkelium',      mass:247, group:3,  period:7, cat:'actinide',    col:11, row:9},
  {z:98, sym:'Cf', name:'Californium',    mass:251, group:3,  period:7, cat:'actinide',    col:12, row:9},
  {z:99, sym:'Es', name:'Einsteinium',    mass:252, group:3,  period:7, cat:'actinide',    col:13, row:9},
  {z:100,sym:'Fm', name:'Fermium',        mass:257, group:3,  period:7, cat:'actinide',    col:14, row:9},
  {z:101,sym:'Md', name:'Mendelevium',    mass:258, group:3,  period:7, cat:'actinide',    col:15, row:9},
  {z:102,sym:'No', name:'Nobelium',       mass:259, group:3,  period:7, cat:'actinide',    col:16, row:9},
  {z:103,sym:'Lr', name:'Lawrencium',     mass:262, group:3,  period:7, cat:'actinide',    col:17, row:9},
  {z:104,sym:'Rf', name:'Rutherfordium',  mass:267, group:4,  period:7, cat:'transition',  col:4,  row:7},
  {z:105,sym:'Db', name:'Dubnium',        mass:268, group:5,  period:7, cat:'transition',  col:5,  row:7},
  {z:106,sym:'Sg', name:'Seaborgium',     mass:269, group:6,  period:7, cat:'transition',  col:6,  row:7},
  {z:107,sym:'Bh', name:'Bohrium',        mass:270, group:7,  period:7, cat:'transition',  col:7,  row:7},
  {z:108,sym:'Hs', name:'Hassium',        mass:277, group:8,  period:7, cat:'transition',  col:8,  row:7},
  {z:109,sym:'Mt', name:'Meitnerium',     mass:278, group:9,  period:7, cat:'transition',  col:9,  row:7},
  {z:110,sym:'Ds', name:'Darmstadtium',   mass:281, group:10, period:7, cat:'transition',  col:10, row:7},
  {z:111,sym:'Rg', name:'Roentgenium',    mass:282, group:11, period:7, cat:'transition',  col:11, row:7},
  {z:112,sym:'Cn', name:'Copernicium',    mass:285, group:12, period:7, cat:'transition',  col:12, row:7},
  {z:113,sym:'Nh', name:'Nihonium',       mass:286, group:13, period:7, cat:'post-trans',  col:13, row:7},
  {z:114,sym:'Fl', name:'Flerovium',      mass:289, group:14, period:7, cat:'post-trans',  col:14, row:7},
  {z:115,sym:'Mc', name:'Moscovium',      mass:290, group:15, period:7, cat:'post-trans',  col:15, row:7},
  {z:116,sym:'Lv', name:'Livermorium',    mass:293, group:16, period:7, cat:'post-trans',  col:16, row:7},
  {z:117,sym:'Ts', name:'Tennessine',     mass:294, group:17, period:7, cat:'halogen',     col:17, row:7},
  {z:118,sym:'Og', name:'Oganesson',      mass:294, group:18, period:7, cat:'noble',       col:18, row:7},
];

